import { ICard } from './types/interface';

const data: ICard[] = [
    {
        id: 1,
        name: 'Властелин Колец: Братство Кольца',
        author: 'Джон Толкин',
        genre: 'Фэнтези',
        img: './assets/img/lordofringsbratstvo.jpg',
        year: 2018,
        price: 757,
        binding: 'Твердый',
        pages: 480,
        lang: 'Русский',
    },
    {
        id: 2,
        name: 'Властелин Колец: Возвращение Короля',
        author: 'Джон Толкин',
        genre: 'Фэнтези',
        img: './assets/img/lordofringsking.jpg',
        year: 2020,
        price: 535,
        binding: 'Твердый',
        pages: 384,
        lang: 'Русский',
    },
    {
        id: 3,
        name: 'Игра престолов',
        author: 'Джордж Мартин',
        genre: 'Фэнтези',
        img: './assets/img/igra_prestolov.jpg',
        year: 2019,
        price: 360,
        binding: 'Твердый',
        pages: 768,
        lang: 'Русский',
    },
    {
        id: 4,
        name: "Alice's Adventures in Wonderland",
        author: 'Льюис Кэрролл',
        genre: 'Фэнтези',
        img: './assets/img/alicesadventures.jpg',
        year: 2008,
        price: 572,
        binding: 'Твердый',
        pages: 178,
        lang: 'Английский',
    },
    {
        id: 5,
        name: "Harry Potter and the Philosopher's Stone",
        author: 'Джоан Роулинг',
        genre: 'Фэнтези',
        img: './assets/img/hp&philstone.jpg',
        year: 2014,
        price: 845,
        binding: 'Твердый',
        pages: 352,
        lang: 'Английский',
    },
    {
        id: 6,
        name: 'Harry Potter and the Deathly Hallows. Hufflepuff Edition',
        author: 'Джоан Роулинг',
        genre: 'Фэнтези',
        img: './assets/img/hp&deathlyhallows.jpg',
        year: 2021,
        price: 620,
        binding: 'Мягкий',
        pages: 640,
        lang: 'Английский',
    },
    {
        id: 7,
        name: 'Убийства на улице Морг',
        author: 'Эдгар Аллан По',
        genre: 'Детектив',
        img: './assets/img/killingsmorg.jpg',
        year: 2016,
        price: 149,
        binding: 'Мягкий',
        pages: 288,
        lang: 'Русский',
    },
    {
        id: 8,
        name: 'Записки о Шерлоке Холмсе',
        author: 'Артур Конан Дойл',
        genre: 'Детектив',
        img: './assets/img/sherlock.jpg',
        year: 2016,
        price: 146,
        binding: 'Мягкий',
        pages: 384,
        lang: 'Русский',
    },
    {
        id: 9,
        name: 'Код да Винчи',
        author: 'Дэн Браун',
        genre: 'Детектив',
        img: './assets/img/kod_davinchi.jpeg',
        year: 2009,
        price: 597,
        binding: 'Твердый',
        pages: 544,
        lang: 'Русский',
    },
    {
        id: 10,
        name: 'Десять негритят',
        author: 'Агата Кристи',
        genre: 'Детектив',
        img: './assets/img/desyat-negrityat.jpg',
        year: 2016,
        price: 359,
        binding: 'Мягкий',
        pages: 256,
        lang: 'Русский',
    },
    {
        id: 11,
        name: 'Левиафан',
        author: 'Борис Акунин',
        genre: 'Детектив',
        img: './assets/img/Leviafan.jpg',
        year: 2015,
        price: 277,
        binding: 'Твердый',
        pages: 240,
        lang: 'Русский',
    },
    {
        id: 12,
        name: 'Янголи і демони',
        author: 'Дэн Браун',
        genre: 'Детектив',
        img: './assets/img/yangoli-i-demoni.jpg',
        year: 2018,
        price: 263,
        binding: 'Твердый',
        pages: 768,
        lang: 'Украинский',
    },
    {
        id: 13,
        name: 'Бойцовский клуб',
        author: 'Чак Паланик',
        genre: 'Триллер',
        img: './assets/img/bojtsovskij-klub.jpg',
        year: 2016,
        price: 409,
        binding: 'Твердый',
        pages: 256,
        lang: 'Русский',
    },
    {
        id: 14,
        name: 'Сяйво',
        author: 'Стивен Кинг',
        genre: 'Триллер',
        img: './assets/img/shining.jpg',
        year: 2019,
        price: 265,
        binding: 'Твердый',
        pages: 640,
        lang: 'Украинский',
    },
    {
        id: 15,
        name: 'Молчание ягнят',
        author: 'Томас Харрис',
        genre: 'Триллер',
        img: './assets/img/molchanie-yagnyat.jpg',
        year: 2016,
        price: 377,
        binding: 'Твердый',
        pages: 416,
        lang: 'Русский',
    },
    {
        id: 16,
        name: 'Остров проклятых',
        author: 'Деннис Лихэйн',
        genre: 'Триллер',
        img: './assets/img/ostrov-proklyatyh.jpg',
        year: 2020,
        price: 389,
        binding: 'Твердый',
        pages: 384,
        lang: 'Русский',
    },
    {
        id: 17,
        name: 'Психо',
        author: 'Роберт Блох',
        genre: 'Триллер',
        img: './assets/img/psyho.jpg',
        year: 2021,
        price: 199,
        binding: 'Твердый',
        pages: 144,
        lang: 'Русский',
    },
    {
        id: 18,
        name: 'Зелена миля',
        author: 'Стивен Кинг',
        genre: 'Фантастика',
        img: './assets/img/greenmile.jpg',
        year: 2018,
        price: 230,
        binding: 'Твердый',
        pages: 432,
        lang: 'Украинский',
    },
    {
        id: 19,
        name: '451 градус по Фаренгейту',
        author: 'Рэй Брэдбери',
        genre: 'Фантастика',
        img: './assets/img/451-gradus-po-farengejtu.jpg',
        year: 2017,
        price: 423,
        binding: 'Твердый',
        pages: 320,
        lang: 'Русский',
    },
    {
        id: 20,
        name: '1984',
        author: 'Джордж Оруэлл',
        genre: 'Фантастика',
        img: './assets/img/1984.jpg',
        year: 2011,
        price: 577,
        binding: 'Твердый',
        pages: 448,
        lang: 'Английский',
    },
    {
        id: 21,
        name: 'Цветы для Элджернона',
        author: 'Дэниел Киз',
        genre: 'Фантастика',
        img: './assets/img/Tsveti-dlya-Eldjernona.jpg',
        year: 2013,
        price: 428,
        binding: 'Твердый',
        pages: 384,
        lang: 'Русский',
    },
    {
        id: 22,
        name: 'Собачье сердце',
        author: 'Михаил Булгаков',
        genre: 'Фантастика',
        img: './assets/img/sobache-serdtse_8ef.jpg',
        year: 2012,
        price: 201,
        binding: 'Мягкий',
        pages: 352,
        lang: 'Русский',
    },
    {
        id: 23,
        name: 'Метро 2033',
        author: 'Дмитрий Глуховский',
        genre: 'Фантастика',
        img: './assets/img/metro-2033_09b.jpg',
        year: 2020,
        price: 593,
        binding: 'Твердый',
        pages: 384,
        lang: 'Русский',
    },
    {
        id: 24,
        name: 'Робинзон Крузо',
        author: 'Даниэль Дефо',
        genre: 'Приключения',
        img: './assets/img/robinzon-kruzo_679.jpg',
        year: 2011,
        price: 392,
        binding: 'Твердый',
        pages: 208,
        lang: 'Русский',
    },
    {
        id: 25,
        name: 'Острів Скарбів',
        author: 'Роберт Льюис Стивенсон',
        genre: 'Приключения',
        img: './assets/img/ostriv-skarbiv_88d.jpg',
        year: 2018,
        price: 196,
        binding: 'Твердый',
        pages: 272,
        lang: 'Украинский',
    },
    {
        id: 26,
        name: 'Морской волк',
        author: 'Джек Лондон',
        genre: 'Приключения',
        img: './assets/img/morskoj-volk_b71.jpg',
        year: 2010,
        price: 153,
        binding: 'Мягкий',
        pages: 416,
        lang: 'Русский',
    },
    {
        id: 27,
        name: 'Пятнадцатилетний капитан',
        author: 'Жюль Верн',
        genre: 'Приключения',
        img: './assets/img/pyatnadtsatiletnij-kapitan-2014_3.jpg',
        year: 2014,
        price: 410,
        binding: 'Твердый',
        pages: 608,
        lang: 'Русский',
    },
    {
        id: 28,
        name: 'Love of Life',
        author: 'Джек Лондон',
        genre: 'Приключения',
        img: './assets/img/love-of-life_08a.jpg',
        year: 2018,
        price: 345,
        binding: 'Твердый',
        pages: 174,
        lang: 'Английский',
    },
];

export default data;
